import type { Metadata } from "next";
import localFont from "next/font/local";
import '@rainbow-me/rainbowkit/styles.css';
import "./globals.css";
import Header from "./_components/Header";
import BlockChainProvider from "@/blockchain/BlockChainProvider";
import dynamic from "next/dynamic";
import ThemeProvider from "@/providers/ThemeProvider";
import Sidebar from "./_components/Sidebar";
const BorrowingPopup = dynamic(() => import("@/components/popup/BorrowingPopup"));
const LendingPopup = dynamic(() => import("@/components/popup/LendingPopup"));

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Trading Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="light" attribute="class" enableSystem disableTransitionOnChange>
          <BlockChainProvider>
            <Header />
            {children}
            <Sidebar />
            <BorrowingPopup />
            <LendingPopup />
          </BlockChainProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
